---
- name: Test
  hosts: JuniperDevices

  tasks:
    - name: Gather legacy and resource facts
      junipernetworks.junos.junos_facts:
        gather_subset: all
        gather_network_resources: all
      become: true


    - name: Print the gateway for each host when defined
      ansible.builtin.debug:
        var: ansible_facts
      become: true
